os: linux
dist: bionic
language: bash
bash:
  - "4.4"

before_install:
  - "sudo apt update"
  - "sudo apt install -y r-base libgd-dev"
  - "cpanm --sudo -v --installdeps --notest --cpanfile cpanfile ."

before_script:
  - "make install_auto"

script:
  - "make test"

notifications:
  email:
    on_failure: always
