os: linux
dist: focal
language: perl
perl:
- 5.30.0
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
- sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'
- sudo apt update
- sudo apt install -y libssl-dev libcurl4-openssl-dev curl build-essential bc make
  g++ r-base r-base-dev python2.7 python2.7-dev
- cpanm --sudo -v --installdeps --notest --cpanfile cpanfile .
before_script:
- sudo make install
script:
- make test
notifications:
  email:
    on_failure: always
env:
  global:
  - secure: FPVcZ07L2ZSaa5KLYms3iFa3+6IytBL7VZVRWxcNlKZHp+/6VTLofRdriSOVWmXy3Oy+A8jp4el56evn6DQt92JmkUZkvZl4X2l22zytvPRFbw76xzSvR171e4Dcnxj4DOUgfuisZEuXHZQKqkt9dyDRG9OYAGouHR98VBOSR1z0ZVy11VvFWnVmE6nef8GrFIQlRzNGmbR7GWnyzY4I/YUxY1jHMJVmjUu7N1hThtKRzdwAYOO2h5QGxqKdEUH07FggM1nDbCWcu/CrsRb1MqIEnyJZIW5RWns93Tai5pDaAVYAq+t2qmXCwNLIJ+wDOQhnIuEXs7MFymRQH1edX8tcGIoLeAfJgkeJt28pXp00FVxn66dF7YmAK4nWWevISvxNvfSZJlYWrUp0mvO9aMP8u2i/BbobtP8X6jUQuKgplQJOJI/N1TgraO/Wx9RQE2wiuvUNnw1XFdoPHABJ/J1ZkYdeZABK9dL1s1cEsG8dgHoLD0OFzWp8tVsUqvOTtc2sAD6iHUCcaxD7GaJ+ElXlTDFdFLapDWmtLz+xGDg+qADkQ46gGINeRK//cni00Q/JOjfd/z7mYPsz4yspS0ejnT2ZMz1LBHXkPcSlR7WbXEr+/Hr9p9HDzZgLKt/PwP7tZHtdXb8i2viI64l9qUJnl0XItjZ7fxAdKqQVp8s=
  - secure: WDwvAF7rE+p64xLcb7bnatRhRTyh2Zw8sZ2PdfIKoyQZkIN07Fz/vl6dYTxMZR0nXD5R5oDjBZeyxN6QmtjzWWyV9ywm0YIDSXjZ8qY/DHoj520JWFLfGgRfw4QcJLok9+t0hGlhJItlNR6mx4ECjMnjVj0QuqOQfCHQcOQS73DCVSf8wqRv2X7vTH4dPM4zIBUaBSEdOyWmvLeOkWYmfQwhuC++8Bg3WE0+UVxA1wkyQctCOVP3icFa7mo78OzPLG9Vz1P0FjQs4ISPVP4UT5zRrOZP/OY/+l2Y21ZRgUo03oc/mSLUS32Larl3XJXv/mcQOYCG9ZdNKDnwWf9lyg8imMes7asg/61wNMOWTEBzUdG3CZdx67O57rwcW79RR/CVNTJuum1wY7N3zCMgmR0aIhN7o+1HM8AX2Y9Q87doET/go4V25FA212RUER05QdRnF4kJOC+VdXKrbzwMpSFG5opEHJDmv0fp9c0Fa3nUDOdEgkaKYTWQj59ON1pBKzZ2zNYaNr9RHqSto+Q4xBL+0nPwaNpk1/rJM6JCkY3u2BGDPjvtcblTgtJsoEZeGDxnKjeUnXKgqGiS76TDWqSL85ho5hYhPhFDvdLDnCq/hI4Rp5qAV55XnCDchl2tXD5t6U6M4cJKAbv91eN2v1bxz6v55HRAfIW73x2G/p8=
