os: linux
dist: focal
language: perl
perl:
  - "5.30" 


before_install:
  - "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9"
  - "sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu focal-cran40/'"
  - "sudo apt-get update"
  - "sudo apt-get install -y libssl-dev libcurl4-openssl-dev curl build-essential bc make g++ r-base r-base-dev python2.7 python2.7-dev"
  - "cpanm --sudo -v --installdeps --notest --cpanfile cpanfile ."

before_script:
  - "make install"

script:
  - "make test"

notifications:
  email:
    on_failure: always
