os: linux
dist: jammy
language: perl
perl:
- 5.22.0
before_install:
- sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
- sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/'
- sudo apt update
- sudo apt install -y libssl-dev libcurl4-openssl-dev curl build-essential bc make
  g++ r-base r-base-dev python2.7 python2.7-dev
- cpanm --sudo -v --installdeps --notest --cpanfile cpanfile .
before_script:
- sudo apt autoremove
- sudo make install
script:
- make test
notifications:
  email:
    on_failure: always
env:
  global:
    secure: Z8glae2caN51axlJWnX0fdhiyR8EagVk09aUmhF3OgKhpraoBa3gyEilDS0lx0grAfzD7Zm/V3Uvt9ne6riBleCmnDLNDSbnB4z7sXYS8TYV+YObVv458ZLO82NKMhMFxMNfMMt4Xi4EO9A3RpXDacfUZsjg642l9b4g2sLoImR9tmAyVnDJBlR0I4ryXMarlLh/QME+xrz5RUtM6ZXZKwaxccxlqQSRg84IbeNlwVvfT50iOHge6aPzr5JL6iRyP7DOjvg8Te3McPOmo/KTWn5Kjj9H1ct4LnfksaeJPQrL5hKRd0EZYykLwARoTAc6iBdQMf9JHJ91HlLpxenPoeNa/jjh4IY1fow/KKtHC5LG/4kUACkp5XIf3io/c08BymsEGkN3MnqwR2L8+FziGLx0xvzpHfOo2e6+kXfaBMExLw0h8aDQxgea+bxQcO8MemC62pHf3NQNHaRoPgCouGTb9isixXO1Scel5LjBK0p6VpAuGtlztsuts6LPNARbsOCr/CDtC2iystveffGVPK9G3i4AGtu9TzuZOuOxxzDiCCMLJ5vkRDdSTmZuUCdjYNGTfKuh8pfZnlIXQGmdw7AM9g8O6cH4cCPRNAudMe8VHoWJNDgDKd1pSVuPKVaIwKCBZnRA782cN5U5PAUa39UluAeIRScRx8bFNCYS+AQ=
