os: linux
dist: bionic
language: perl
perl:
  - "5.26"

before_install:
  - "sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9"
  - "sudo add-apt-repository -y https://cloud.r-project.org/bin/linux/ubuntu/bionic-cran35"
  - "sudo apt-get update"
  - "sudo apt-get install -y g++ r-base r-base-dev"
  - "cpanm --sudo -v --installdeps --notest --cpanfile cpanfile ."

before_script:
  - "make install"

script:
  - "make test"

notifications:
  email:
    on_failure: always
